### ISSUE TITLE
Thanks for informing about flexboxfroggy

### ISSUE THREAD

**Issue by RitamChakraborty** [RishikaGhosh/RishikaGhosh#3]
First of all it's not an issue. 

I just wanted to thank you for informing about [flexboxfroggy](https://flexboxfroggy.com). I actually like css games and personally play [CSSBattle](https://cssbattle.dev). So finding something similar, I found myself very excited. 

I stumble upon your profile while creating a pull request in [creative-profile-readme](https://github.com/coderjojo/creative-profile-readme). Anyways thanks for the website again, if you know something similar please let me know.

**Comment by RishikaGhosh** [comment]
Im glad that it helped! I didnt know about CSSBattle myself and its definitely cool! So thanks to you too.
